spring:
    profiles:
        active: dev
    redis:
        host: 127.0.0.1
        port: 6379
        timeout: 5000
        database: 0
        password:
server:
    tomcat:
        uri-encoding: UTF-8
    servlet:
        encoding:
            charset: UTF-8
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:///kernel_data_lizp?useSSL=false&serverTimezone=UTC
        username: root
        password: wzzwzz020410
        type: com.alibaba.druid.pool.DruidDataSource
server:
    port: 80
logging:
    level:
        root: warn
---
spring:
    config:
        activate:
            on-profile: test
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.4:3306/kernel_data_lizp?useSSL=false&serverTimezone=UTC
        username: root
        password: wzzwzz020410
        type: com.alibaba.druid.pool.DruidDataSource
server:
    port: 80
---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.4:3306/kernel_data_lizp?useSSL=false&serverTimezone=UTC
        username: root
        password: wzzwzz020410
        type: com.alibaba.druid.pool.DruidDataSource
server:
    port: 8081